rankings = [
    'A Bar Song (Tipsy)'
    , 'I Had Some Help'
    , 'Lies Lies Lies'
    , 'Pink Skies'
    , '28'
    , 'Cowgirls'
    , 'Miles On It'
    , 'American Nights'
    , 'I Remember Everything'
    , 'Austin'
    , 'Pour Me A Drink'
    , 'Whiskey Whiskey'
    , "Ain't No Love In Oklahoma"
    , 'I Am Not Okay'
    , 'High Road'
    , 'You Look Like You Love Me'
    , 'Better Days'
    , 'Oak Island'
    , 'Dirt Cheap'
    , 'Bulletproof'
    , 'We Ride'
    , 'The Way Back'
    , 'The Great American Bar Scene'
    , 'Bass Boat'
    , 'Purple Gas'
    , 'Sandpaper'
    , 'Mechanical Bull'
    , 'Boons'
    , "Wind Up Missin' You"
    , 'Wine Into Whiskey'
    , 'Memphis; The Blues'
    , 'Cowboys Cry Too'
    , 'Hang Tight Honey'
    , "Think I'm In Love With You"
    , 'Sweet Dreams'
    , 'Chevrolet'
    , 'Like Ida'
    , 'Northern Thunder'
    , 'Towers'
    , 'Beautiful As You'
    , 'Funny Man'
    , 'Remember Him That Way'
    , 'Lucky Enough (Poem)'
    , 'Holy Smokes'
    , 'Bathwater'
    , 'New To Country'
    , 'Nine Ball'
    , 'Young Love & Saturday Nights'
    , 'Devil You Know'
    , 'Love You Again'
]
