rankings = [ # 2024-03-26
    "Texas Hold 'Em"
    , 'I Remember Everything'
    , 'Last Night'
    , 'Fast Car'
    , "Thinkin' Bout Me"
    , 'Truck Bed'
    , 'Man Made A Bar'
    , 'Wild Ones'
    , 'Pretty Little Poison'
    , 'Where The Wild Things Are'
    , 'Burn It Down'
    , '23'
    , 'Wildflowers And Wild Horses'
    , "Mamaw's House"
    , 'Austin'
    , 'I Can Feel It'
    , 'Deeper Well'
    , 'Spin You Around (1/24)'
    , 'Tucson Too Late'
    , 'Back Then Right Now'
    , 'Coal'
    , 'Outskirts'
    , 'Holy Smokes'
    , 'We Ride'
    , "We Don't Fight Anymore"
    , 'Wine Into Whiskey'
    , 'Wondering Why'
    , 'Halfway To Hell'
    , 'Too Good To Be True'
    , 'Cab In A Solo'
    , 'No Caller ID'
    , 'Take Her Home'
    , 'Cardinal'
    , 'Your Place'
    , 'Dirt Cheap'
    , 'Smoke & A Light'
    , "I'm Not Pretty"
    , 'The Architect'
    , 'Bulletproof'
    , "Think I'm In Love With You"
    , 'In Your Love'
    , 'Fearless (The Echo)'
    , 'Damn Near Normal'
    , 'Love You Again'
    , "This Town's Been Too Good To Us"
    , 'Let Your Boys Be Country'
    , 'Boys Back Home'
    , '16 Carriages'
    , 'Chevrolet'
    , 'Creek Will Rise'
]
