rankings = [
    'A Bar Song (Tipsy)'
    , 'I Had Some Help'
    , 'Cowgirls'
    , 'Pink Skies'
    , 'Pour Me A Drink'
    , 'I Remember Everything'
    , 'Miles On It'
    , 'Austin'
    , 'Whiskey Whiskey'
    , 'High Road'
    , 'I Am Not Okay'
    , "Ain't No Love In Oklahoma"
    , 'You Look Like You Love Me'
    , 'Dirt Cheap'
    , 'Bulletproof'
    , 'Cowboys Cry Too'
    , 'We Ride'
    , 'Wine Into Whiskey'
    , "Wind Up Missin' You"
    , "Think I'm In Love With You"
    , 'Sweet Dreams'
    , 'Let Your Boys Be Country'
    , 'Chevrolet'
    , 'Beautiful As You'
    , 'Remember Him That Way'
    , 'Hang Tight Honey'
    , 'New To Country'
    , 'Holy Smokes'
    , 'Purple Gas'
    , 'Relapse'
    , 'Devil You Know'
    , 'Worst Way'
    , 'Nine Ball'
    , 'The Man He Sees In Me'
    , "What He'll Never Have"
    , 'Young Love & Saturday Nights'
    , "I'm Not Pretty"
    , 'Love You Again'
    , 'Love You, Miss You, Mean It'
    , "She's Somebody's Daughter (Reimagined)"
    , 'Smoke & A Light'
    , 'Indifferent'
    , 'Boys Back Home'
    , 'Sun To Me'
    , 'American Nights'
    , 'Coming Home'
    , '28'
    , "Song While You're Away"
    , 'Maxed Out'
    , 'Wanna Be Loved'
]
