rankings = [ # 2025-10-14
    'I Got Better'
    , 'What I Want'
    , "I'm The Problem"
    , 'Just In Case'
    , 'Good News'
    , 'Bar None'
    , 'Back In The Saddle'
    , 'All The Way'
    , 'Happen To Me'
    , 'Bottle Rockets'
    , 'Hell At Night'
    , 'House Again'
    , '6 Months Later'
    , 'Somewhere Over Laredo'
    , 'Heart Of Stone'
    , 'Last One To Know'
    , "Don't Mind If I Do"
    , 'Better Me For You (Brown Eyes)'
    , "Darlin'"
    , 'Hard Fought Hallelujah'
    , 'The Fall'
    , '20 Cigarettes'
    , 'What Kinda Man'
    , 'Backup Plan'
    , 'Days Like These'
    , 'Amen'
    , 'Holy Water'
    , "I Ain't Coming Back"
    , 'Brunette'
    , 'How Far Does A Goodbye Go'
    , '3,2,1'
    , 'Good Times & Tan Lines'
    , 'Heavens To Betsy'
    , 'Favorite Country Song'
    , 'Miami' # ft Rick Ross and Lil Wayne
    , 'A Song To Sing'
    , 'Hands Of Time'
    , 'Keeps Me Sane'
    , 'South Of Sanity'
    , 'Bottomland'
    , 'Ends Of The Earth'
    , 'Sober'
    , 'Cowgirl'
    , 'Need To'
    , 'Ordinary'
    , '15 Minutes'
    , 'Painted You Pretty'
    , "People Hatin'"
    , 'Lost'
    , 'Damned If I Do'
]
